plugins {
    id 'org.springframework.boot' version '4.1.1' apply false
}

ext {
    springBootVersion = '4.1.1'
    wiremockVersion = '3.13.2'
    springdocVersion = '3.1.1'
}

subprojects {
    group = 'com.brokers'
    version = '0.1.0'

    apply plugin: 'java-library'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        implementation platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
        testImplementation platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
        testImplementation 'org.junit.jupiter:junit-jupiter'
        testImplementation 'org.assertj:assertj-core'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.compilerArgs += ['-parameters', '-Xlint:unchecked']
    }

    tasks.named('test') {
        useJUnitPlatform()
        testLogging {
            events 'failed'
            exceptionFormat 'full'
        }
    }
}
