-- Brokers platform schema.
-- Written in portable SQL so it runs on PostgreSQL (production) and H2 in PostgreSQL mode (dev/tests).
-- Conventions:
--   * UUID primary keys generated by the application.
--   * Every tenant-owned table carries organization_id so queries can always be scoped to one tenant.
--   * created_at / updated_at are UTC timestamps; version supports optimistic locking.
--   * Enumerations are VARCHAR with CHECK constraints so values stay readable and evolvable.

-- ---------------------------------------------------------------------------------------------
-- Tenancy and authentication
-- ---------------------------------------------------------------------------------------------

create table organizations (
    id               uuid         not null,
    name             varchar(160) not null,
    slug             varchar(80)  not null,
    default_currency varchar(3)   not null,
    timezone         varchar(64)  not null,
    status           varchar(20)  not null,
    created_at       timestamp with time zone not null,
    updated_at       timestamp with time zone not null,
    version          bigint       not null default 0,
    constraint pk_organizations primary key (id),
    constraint uq_organizations_slug unique (slug),
    constraint ck_organizations_status check (status in ('ACTIVE', 'SUSPENDED')),
    constraint ck_organizations_currency check (length(default_currency) = 3)
);

create table organization_members (
    id                    uuid         not null,
    organization_id       uuid         not null,
    email                 varchar(254) not null,
    password_hash         varchar(100) not null,
    full_name             varchar(160) not null,
    role                  varchar(20)  not null,
    failed_login_attempts integer      not null default 0,
    locked_until          timestamp with time zone,
    last_login_at         timestamp with time zone,
    created_at            timestamp with time zone not null,
    updated_at            timestamp with time zone not null,
    version               bigint       not null default 0,
    constraint pk_organization_members primary key (id),
    constraint fk_members_organization foreign key (organization_id) references organizations (id) on delete cascade,
    -- Emails are stored lower-cased by the application, so a plain unique constraint is case-insensitive.
    constraint uq_members_email unique (email),
    -- One login per organization for now; drop this constraint to allow teams.
    constraint uq_members_organization unique (organization_id),
    constraint ck_members_role check (role in ('OWNER')),
    constraint ck_members_failed_attempts check (failed_login_attempts >= 0)
);

create table auth_sessions (
    id           uuid        not null,
    member_id    uuid        not null,
    -- SHA-256 of the bearer token; the token itself is never stored.
    token_hash   varchar(64) not null,
    user_agent   varchar(255),
    ip_address   varchar(45),
    created_at   timestamp with time zone not null,
    expires_at   timestamp with time zone not null,
    revoked_at   timestamp with time zone,
    constraint pk_auth_sessions primary key (id),
    constraint fk_sessions_member foreign key (member_id) references organization_members (id) on delete cascade,
    constraint uq_sessions_token_hash unique (token_hash),
    constraint ck_sessions_expiry check (expires_at > created_at)
);

create index ix_sessions_member on auth_sessions (member_id);

-- ---------------------------------------------------------------------------------------------
-- Channel connections
-- ---------------------------------------------------------------------------------------------

create table channel_connections (
    id                       uuid          not null,
    organization_id          uuid          not null,
    channel                  varchar(20)   not null,
    status                   varchar(30)   not null,
    account_id               varchar(100)  not null,
    -- Secrets are AES-GCM encrypted by the application ("v1:<base64 iv+ciphertext>").
    api_key_encrypted        varchar(1024) not null,
    api_secret_encrypted     varchar(1024) not null,
    webhook_secret_encrypted varchar(1024) not null,
    last_verified_at         timestamp with time zone,
    last_error               varchar(1000),
    created_at               timestamp with time zone not null,
    updated_at               timestamp with time zone not null,
    version                  bigint        not null default 0,
    constraint pk_channel_connections primary key (id),
    constraint fk_connections_organization foreign key (organization_id) references organizations (id) on delete cascade,
    constraint uq_connections_org_channel unique (organization_id, channel),
    -- A supplier account on a channel belongs to exactly one organization.
    constraint uq_connections_channel_account unique (channel, account_id),
    constraint ck_connections_channel check (channel in ('BOOKING', 'RENTALCARS')),
    constraint ck_connections_status check (status in ('CONNECTED', 'INVALID_CREDENTIALS', 'DISCONNECTED'))
);

-- ---------------------------------------------------------------------------------------------
-- Fleet
-- ---------------------------------------------------------------------------------------------

create table locations (
    id              uuid          not null,
    organization_id uuid          not null,
    code            varchar(40)   not null,
    name            varchar(160)  not null,
    address_line    varchar(255)  not null,
    city            varchar(120)  not null,
    postal_code     varchar(20),
    country_code    varchar(2)    not null,
    latitude        numeric(9, 6),
    longitude       numeric(9, 6),
    iata_code       varchar(3),
    created_at      timestamp with time zone not null,
    updated_at      timestamp with time zone not null,
    version         bigint        not null default 0,
    constraint pk_locations primary key (id),
    constraint fk_locations_organization foreign key (organization_id) references organizations (id) on delete cascade,
    constraint uq_locations_org_code unique (organization_id, code),
    constraint ck_locations_country check (length(country_code) = 2),
    constraint ck_locations_iata check (iata_code is null or length(iata_code) = 3),
    constraint ck_locations_latitude check (latitude is null or latitude between -90 and 90),
    constraint ck_locations_longitude check (longitude is null or longitude between -180 and 180)
);

create table vehicles (
    id               uuid           not null,
    organization_id  uuid           not null,
    location_id      uuid           not null,
    reference        varchar(60)    not null,
    make             varchar(60)    not null,
    model            varchar(60)    not null,
    model_year       integer        not null,
    acriss_code      varchar(4)     not null,
    transmission     varchar(20)    not null,
    fuel_type        varchar(20)    not null,
    seats            integer        not null,
    doors            integer        not null,
    bags             integer        not null,
    air_conditioning boolean        not null,
    -- NULL means unlimited mileage.
    mileage_limit_km integer,
    min_driver_age   integer        not null,
    daily_rate       numeric(12, 2) not null,
    deposit          numeric(12, 2),
    currency         varchar(3)     not null,
    status           varchar(20)    not null,
    created_at       timestamp with time zone not null,
    updated_at       timestamp with time zone not null,
    version          bigint         not null default 0,
    constraint pk_vehicles primary key (id),
    constraint fk_vehicles_organization foreign key (organization_id) references organizations (id) on delete cascade,
    constraint fk_vehicles_location foreign key (location_id) references locations (id),
    constraint uq_vehicles_org_reference unique (organization_id, reference),
    constraint ck_vehicles_year check (model_year between 1990 and 2100),
    constraint ck_vehicles_acriss check (length(acriss_code) = 4),
    constraint ck_vehicles_transmission check (transmission in ('MANUAL', 'AUTOMATIC')),
    constraint ck_vehicles_fuel check (fuel_type in ('PETROL', 'DIESEL', 'HYBRID', 'ELECTRIC', 'LPG')),
    constraint ck_vehicles_seats check (seats between 1 and 60),
    constraint ck_vehicles_doors check (doors between 2 and 6),
    constraint ck_vehicles_bags check (bags between 0 and 20),
    constraint ck_vehicles_mileage check (mileage_limit_km is null or mileage_limit_km > 0),
    constraint ck_vehicles_driver_age check (min_driver_age between 18 and 99),
    constraint ck_vehicles_daily_rate check (daily_rate > 0),
    constraint ck_vehicles_deposit check (deposit is null or deposit >= 0),
    constraint ck_vehicles_currency check (length(currency) = 3),
    constraint ck_vehicles_status check (status in ('DRAFT', 'ACTIVE', 'ARCHIVED'))
);

create index ix_vehicles_org_status on vehicles (organization_id, status);
create index ix_vehicles_location on vehicles (location_id);

create table vehicle_photos (
    id         uuid          not null,
    vehicle_id uuid          not null,
    url        varchar(2048) not null,
    caption    varchar(200),
    position   integer       not null,
    created_at timestamp with time zone not null,
    constraint pk_vehicle_photos primary key (id),
    constraint fk_photos_vehicle foreign key (vehicle_id) references vehicles (id) on delete cascade,
    constraint ck_photos_position check (position >= 0)
);

create index ix_photos_vehicle on vehicle_photos (vehicle_id, position);

-- ---------------------------------------------------------------------------------------------
-- Channel listings: one row per vehicle per channel, holding the channel's identifier and the
-- fingerprints of what was last pushed so unchanged data is never re-sent.
-- ---------------------------------------------------------------------------------------------

create table channel_listings (
    id                uuid          not null,
    organization_id   uuid          not null,
    vehicle_id        uuid          not null,
    channel           varchar(20)   not null,
    external_id       varchar(120),
    status            varchar(20)   not null,
    content_hash      varchar(64),
    photos_hash       varchar(64),
    availability_hash varchar(64),
    last_synced_at    timestamp with time zone,
    last_error        varchar(1000),
    created_at        timestamp with time zone not null,
    updated_at        timestamp with time zone not null,
    version           bigint        not null default 0,
    constraint pk_channel_listings primary key (id),
    constraint fk_listings_organization foreign key (organization_id) references organizations (id) on delete cascade,
    constraint fk_listings_vehicle foreign key (vehicle_id) references vehicles (id) on delete cascade,
    constraint uq_listings_vehicle_channel unique (vehicle_id, channel),
    -- Unique identifiers per channel; NULL (not yet created) is allowed many times.
    constraint uq_listings_channel_external unique (channel, external_id),
    constraint ck_listings_channel check (channel in ('BOOKING', 'RENTALCARS')),
    constraint ck_listings_status check (status in ('PENDING', 'PUBLISHED', 'FAILED', 'UNPUBLISHED'))
);

create index ix_listings_org on channel_listings (organization_id);

-- ---------------------------------------------------------------------------------------------
-- Reservations and availability
-- ---------------------------------------------------------------------------------------------

create table reservations (
    id                      uuid           not null,
    organization_id         uuid           not null,
    vehicle_id              uuid           not null,
    channel                 varchar(20)    not null,
    external_reservation_id varchar(120)   not null,
    status                  varchar(20)    not null,
    pickup_at               timestamp with time zone not null,
    return_at               timestamp with time zone not null,
    customer_name           varchar(200),
    customer_email          varchar(254),
    total_amount            numeric(12, 2),
    currency                varchar(3),
    -- Set when the reservation overlaps another block of the same car (an overbooking to resolve).
    has_conflict            boolean        not null default false,
    -- occurred_at of the latest applied event; older events are ignored to survive out-of-order delivery.
    last_event_at           timestamp with time zone not null,
    created_at              timestamp with time zone not null,
    updated_at              timestamp with time zone not null,
    version                 bigint         not null default 0,
    constraint pk_reservations primary key (id),
    constraint fk_reservations_organization foreign key (organization_id) references organizations (id) on delete cascade,
    constraint fk_reservations_vehicle foreign key (vehicle_id) references vehicles (id),
    constraint uq_reservations_channel_external unique (channel, external_reservation_id),
    constraint ck_reservations_channel check (channel in ('BOOKING', 'RENTALCARS')),
    constraint ck_reservations_status check (status in ('CONFIRMED', 'CANCELLED')),
    constraint ck_reservations_period check (return_at > pickup_at),
    constraint ck_reservations_amount check (total_amount is null or total_amount >= 0),
    constraint ck_reservations_price check ((total_amount is null) = (currency is null))
);

create index ix_reservations_org_pickup on reservations (organization_id, pickup_at);
create index ix_reservations_vehicle on reservations (vehicle_id, pickup_at);

create table availability_blocks (
    id              uuid         not null,
    organization_id uuid         not null,
    vehicle_id      uuid         not null,
    starts_at       timestamp with time zone not null,
    ends_at         timestamp with time zone not null,
    reason          varchar(20)  not null,
    reservation_id  uuid,
    note            varchar(500),
    created_at      timestamp with time zone not null,
    updated_at      timestamp with time zone not null,
    version         bigint       not null default 0,
    constraint pk_availability_blocks primary key (id),
    constraint fk_blocks_organization foreign key (organization_id) references organizations (id) on delete cascade,
    constraint fk_blocks_vehicle foreign key (vehicle_id) references vehicles (id) on delete cascade,
    constraint fk_blocks_reservation foreign key (reservation_id) references reservations (id) on delete cascade,
    constraint uq_blocks_reservation unique (reservation_id),
    constraint ck_blocks_period check (ends_at > starts_at),
    constraint ck_blocks_reason check (reason in ('RESERVATION', 'MAINTENANCE', 'MANUAL')),
    constraint ck_blocks_reservation_link check ((reason = 'RESERVATION') = (reservation_id is not null))
);

create index ix_blocks_vehicle_period on availability_blocks (vehicle_id, starts_at, ends_at);

-- ---------------------------------------------------------------------------------------------
-- Integration plumbing: inbound webhook log and outbound sync job queue (transactional outbox).
-- ---------------------------------------------------------------------------------------------

create table webhook_events (
    id                uuid          not null,
    organization_id   uuid          not null,
    connection_id     uuid          not null,
    channel           varchar(20)   not null,
    external_event_id varchar(160)  not null,
    event_type        varchar(80)   not null,
    payload           varchar(65536) not null,
    status            varchar(20)   not null,
    attempts          integer       not null default 0,
    last_error        varchar(1000),
    received_at       timestamp with time zone not null,
    processed_at      timestamp with time zone,
    constraint pk_webhook_events primary key (id),
    constraint fk_webhooks_organization foreign key (organization_id) references organizations (id) on delete cascade,
    constraint fk_webhooks_connection foreign key (connection_id) references channel_connections (id) on delete cascade,
    -- Channels retry deliveries; this constraint makes processing idempotent.
    constraint uq_webhooks_connection_event unique (connection_id, external_event_id),
    constraint ck_webhooks_channel check (channel in ('BOOKING', 'RENTALCARS')),
    constraint ck_webhooks_status check (status in ('RECEIVED', 'PROCESSED', 'IGNORED', 'FAILED')),
    constraint ck_webhooks_attempts check (attempts >= 0)
);

create index ix_webhooks_org_received on webhook_events (organization_id, received_at);

create table sync_jobs (
    id              uuid          not null,
    organization_id uuid          not null,
    vehicle_id      uuid          not null,
    channel         varchar(20)   not null,
    job_type        varchar(30)   not null,
    status          varchar(20)   not null,
    trigger_reason  varchar(60)   not null,
    -- When true the job pushes even if the fingerprint says nothing changed.
    force           boolean       not null default false,
    attempts        integer       not null default 0,
    max_attempts    integer       not null,
    next_attempt_at timestamp with time zone not null,
    locked_at       timestamp with time zone,
    last_error      varchar(2000),
    completed_at    timestamp with time zone,
    created_at      timestamp with time zone not null,
    updated_at      timestamp with time zone not null,
    version         bigint        not null default 0,
    constraint pk_sync_jobs primary key (id),
    constraint fk_jobs_organization foreign key (organization_id) references organizations (id) on delete cascade,
    constraint fk_jobs_vehicle foreign key (vehicle_id) references vehicles (id) on delete cascade,
    constraint ck_jobs_channel check (channel in ('BOOKING', 'RENTALCARS')),
    constraint ck_jobs_type check (job_type in ('UPSERT_LISTING', 'REPLACE_PHOTOS', 'REPLACE_AVAILABILITY', 'DEACTIVATE_LISTING')),
    constraint ck_jobs_status check (status in ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED')),
    constraint ck_jobs_attempts check (attempts >= 0 and max_attempts > 0 and attempts <= max_attempts)
);

create index ix_jobs_due on sync_jobs (status, next_attempt_at);
create index ix_jobs_org_created on sync_jobs (organization_id, created_at);
create index ix_jobs_coalesce on sync_jobs (vehicle_id, channel, job_type, status);
